version: '3'

services:
  microservice-nikcode-users-auth:
    image: jihnordraven/nikcode-users-auth:latest
    container_name: nikcode-users-auth-contianer
    ports:
      - 3800:3800
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432

  microservice-nikcode-payments:
    image: jihnordraven/nikcode-payments:latest
    container_name: nikcode-payments-container
    ports:
      - 3900:3900
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432

  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
